### ISSUE TITLE
tf happened here

### ISSUE THREAD

**Issue by Errorcrafter** [Acaiberii-archive/goodbye.#1]

**Comment by ghost** [comment]
gamer
i originally left because personal reasons but i decided to come back because why not

**Comment by Errorcrafter** [comment]
k cool

**Comment by Errorcrafter** [comment]
will bakdooro still be maintained? its lacking in a whole bunch of features that i could add for you

**Comment by Errorcrafter** [comment]
5

**Comment by ghost** [comment]
@Errorcrafter  
I made a new organization so we can work together on bakdooro.  
I'm rewriting it now :D
